language: ruby
rvm:
  - 2.1.1
  - 1.9.3
env:
  - 'ADAPTER=activerecord'
  - 'ADAPTER=datamapper'
  - 'ADAPTER=mongoid'
before_script:
  - '[ "$ADAPTER" = "mongoid" ] && service mongodb start || true'
branches:
  only:
    - master
