language: ruby
rvm:
  - 2.1.1
  - 1.9.3
env:
  - 'ADAPTER=activerecord'
  - 'ADAPTER=datamapper'
  - 'ADAPTER=mongoid'
before_script:
  - if [[ "$ADAPTER" == "mongoid" ]]; then service mongodb start; fi
services:
  - mongodb
branches:
  only:
    - master
